### ISSUE TITLE
Prevent adding over 8 hours a day /  Allow filling the day to 8 hour

### ISSUE THREAD

**Issue by lampapetrol** [Khyme/lazy-redmine#4]
Currently the tool let the user enter over the 8 hours mark by day which will end up with the person being lectured by HR.

- Multiple submits
- If you already have some entries in redmine and you want to fill your day on 8h.

This could be solved by checking for each day the sum of hours entered by user and calculate the max number of hours to add to the day:  with feature #3 the tool would add something like Math.min(nbHours, maxHours-existingDailyHours)

**Comment by Khyme** [comment]
5bfea1bf00d7e93cd11edb4c90b3c9a145d8d038

**Comment by lampapetrol** [comment]
that was quick !
